In [1]:
import numpy as np

In [25]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix = np.random.randint(1, 11, size=(5,5))
print(matrix)

[[5 7 9 5 3]
 [2 1 1 3 6]
 [9 7 8 8 6]
 [6 7 5 7 3]
 [3 2 5 8 5]]


In [28]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix = np.random.rand(4,4)
print(matrix)

[[0.46805222 0.67503923 0.59657944 0.61578546]
 [0.98935897 0.93506656 0.9313595  0.19580314]
 [0.85594684 0.27203105 0.81699541 0.73470981]
 [0.06180876 0.65088536 0.73889491 0.79003153]]


In [29]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні 
# операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=(5), dtype=int)
b = np.random.randint(1, 11, size=(5), dtype=int)
print(a+b)
print(a-b)
print(a*b)

[11 12 13 14  9]
[-5  0  7  6  1]
[24 36 30 40 20]


In [12]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([2, 4, 6, 1, 3, 5, 9])
print(np.dot(vector1, vector2))

140


In [30]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,3), dtype=int)
print(np.dot(matrix1, matrix2))

[[60 82 62]
 [46 49 51]]


In [31]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(3,3), dtype=int)
matrix_inv = np.linalg.inv(matrix)
print(matrix_inv)

[[ 0.26666667 -0.03333333 -0.06666667]
 [ 2.2         0.6        -1.8       ]
 [-0.93333333 -0.13333333  0.73333333]]


In [15]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.rand(4, 4)
print(matrix.T)

[[0.72134156 0.42880068 0.23752598 0.83815762]
 [0.60537426 0.49694561 0.6188766  0.38074179]
 [0.77547821 0.64715029 0.24436073 0.85714374]
 [0.03444573 0.61756546 0.96129218 0.49243283]]


In [32]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю 
# на вектор.
matrix = np.random.randint(1, 11, size=(3,4), dtype=int)
vector = np.random.randint(1, 11, size=(4), dtype=int)
print(np.dot(matrix, vector))

[62 87 91]


In [33]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю 
# на вектор.
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print(np.dot(matrix, vector))

[0.30956472 0.58467035]


In [34]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)
print(matrix1*matrix2)

[[70  2]
 [ 9 30]]


In [35]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, size=(2,2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2,2), dtype=int)
print(np.dot(matrix1, matrix2))

[[105  42]
 [108  34]]


In [36]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.random.randint(1, 101, size=(5,5), dtype=int)
print(matrix)
print(matrix.sum())

[[63  8 12 21 72]
 [59 50 25  4 18]
 [31 34 31 96 40]
 [71 38  6 50 88]
 [14 56 60 78 13]]
1038


In [37]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix1 = np.random.randint(1, 11, size=(4,4), dtype=int)
matrix2 = np.random.randint(1, 11, size=(4,4), dtype=int)
print(matrix1 - matrix2)

[[-3  4  8 -3]
 [-5  3 -1 -5]
 [-1 -3  3  5]
 [ 3  2  0 -3]]


In [38]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму
#  елементів кожного рядка матриці.
matrix = np.random.rand(3, 3)
row_sums = matrix.sum(axis=1).reshape(-1, 1)
print(row_sums)

[[0.59640868]
 [0.86972134]
 [1.21392145]]


In [40]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(0, 11, (3, 4))
print(matrix)
matrix2 = matrix ** 2
print(matrix2)

[[0 1 0 8]
 [2 9 3 8]
 [2 8 3 6]]
[[ 0  1  0 64]
 [ 4 81  9 64]
 [ 4 64  9 36]]


In [41]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями
#  цих чисел.
vector1 = np.random.randint(1, 51, size=4)
print(vector1)
vector2 = np.sqrt(vector1)
print(vector2)

[11 43 30  3]
[3.31662479 6.55743852 5.47722558 1.73205081]
